### ISSUE TITLE
Change all download URLs to https

### ISSUE THREAD

**Issue by ygoe** [DomGho/InnoDependencyInstaller#12]
I have recently added a new dependency module (pull request to come) and used the official download URL from Microsoft using https. It works fine on my Windows 7 computer and Windows 10. I haven't done any testing with older (now unsupported) Windows versions so I don't know whether the https support is a new thing.

Nonetheless I consider automatic internet downloads critical to the security of the computer, especially when done from an administrative context with all privileges.

I suggest changing all download URLs in all modules from http to https links. I can provide a pull request if desired.

**Comment by stfx** [comment]
Sure if there is an actual security gain. I guess it is mainly useful to prevent a middleman to modify the received file.

**Comment by dg9ngf** [comment]
That's exactly the security gain. The internet is not a trustworthy network and has never been. Digital certificates in the setup files are displayed to the user only for non-admin execution. Since the dependency installers usually already run from an administrator context, there is no check whatsoever for the downloaded file.

Now using https still relies on the SSL infrastructure which has been partly broken a few times in the past. But at least it is _some_ security.

**Comment by isbslagelwa** [comment]
Afraid https doesn't appear to work on Windows 7. Just get a error, "Unsupported protocol. Only HTTP and FTP protocols are supported."

**Comment by dg9ngf** [comment]
It seems we have to revert that. Since that commit also included other fixes and more commits came in based on that, I'd suggest making a new merge request specifically for this change. Unless somebody finds a way to use HTTPS with Inno Setup. Replacing the stupid old unmaintained isxdl is an option, but with what?

**Comment by isbslagelwa** [comment]
There's a couple listed on the Inno Third-Party page, http://www.jrsoftware.org/is3rdparty.php.  Not sure if any of the other options are any better or were earlier rejected.

**Comment by dg9ngf** [comment]
There are two downloaders on that page with HTTPS support. One is completely free but currently unmaintained. Doesn't look too bad though according to the open issues. It is VS 2005 C++ code that generates a DLL like isxdl. The other is completely written in Inno Script code, no DLL, but it has a not-so-nice license requirement of a web backlink. Which would you prefer?

**Comment by isbslagelwa** [comment]
I'd think not having any DLL requirement would be beneficial.  But I could
see how #4 in the license requirement could be problematic.  I sent them an
email asking about the license, maybe they'll be willing to make an
exception for this use case.

Otherwise I guess its the C++ version.  I asked on their mailing list
whether its still being maintained.



On Mon, Feb 22, 2016 at 11:02 AM, Yves Goergen <notifications@github.com>
wrote:

> There are two downloaders on that page with HTTPS support. One is
> completely free but currently unmaintained. Doesn't look too bad though
> according to the open issues. It is VS 2005 C++ code that generates a DLL
> like isxdl. The other is completely written in Inno Script code, no DLL,
> but it has a not-so-nice license requirement of a web backlink. Which would
> you prefer?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stfx/innodependencyinstaller/issues/12#issuecomment-187321667>
> .
>



-- 
Joe Slagel
Institute for Systems Biology
jslagel@systemsbiology.org

**Comment by nolme** [comment]
Inno Download Plugin (IDP 1.5 works well)
(I've tried to recompile it but it use old MFC application and project don't compile on VS 2015)

**Comment by dg9ngf** [comment]
I've just downloaded their latest source code and opened it in VS 2015. It has upgraded the project and stuff, then it compiled just fine. I commented out the #define in ui.h that has caused some notices. The dlltest project has successfully downloaded a file over http and https. Looks simple. Doesn't require outdated build tools. The project settings say it doesn't use MFC at all. (I'd be surprised what it should be used for anyway.)

**Comment by ygoe** [comment]
Has anything happened here? Otherwise I'm out, unfortunately. I can't find the resources to track this issue and do something about it. .NET is everywhere now and downloading anything is probably not required anymore, so I'm just not going to use it anymore in this insecure state.

**Comment by domgho** [comment]
Inno Setup 6.1 will natively support downloading files with https and sha256 checksum support.

Here is the official example in case someone wants to work on replacing isxdl: https://github.com/jrsoftware/issrc/blob/main/Examples/CodeDownloadFiles.iss

**Comment by Tracy-P** [comment]
Letting this be known as it relates to this open issue:
I have run in to a problem with the http:// in the scripts. When attempting to install on a Windows Server 2016 the download is attempting to redirect to a secure connection. A dialog appears:
![image](https://user-images.githubusercontent.com/47571263/91611409-39cf6900-e949-11ea-9002-704f7a12b9e1.png)

Clicking the "Retry" option just comes right back to the dialog. Clicking the Cancel button returns to the confirmation step.

Changing the 3 scripts to use HTTPS causes the before mentioned error that only HTTP and FTP protocols are supported.
![image](https://user-images.githubusercontent.com/47571263/91612190-e5c58400-e94a-11ea-9c7e-a3a22e9eacab.png)

I am using Inno 5.6.1 (a) because Inno 6.0 gave me a problem with installing a service using APIs. I'm going to spend time attempting to find out why 6.0 isn't working with my API calls.
